packages:
  - SankhyaUI
  - Stories


catalog:
  '@eslint/js': 9.39.1
  '@iconify/react': 6.0.2
  '@storybook/addon-themes': 10.1.11
  '@storybook/addon-docs': 10.1.11
  '@storybook/blocks': 8.6.15
  '@storybook/react-vite': 10.1.11
  '@tailwindcss/vite': 4.1.18
  '@types/node': 24.10.1
  '@types/react': 19.2.5
  '@types/react-dom': 19.2.3
  '@vitejs/plugin-react': 5.1.1
  eslint: 9.39.1
  eslint-plugin-react-hooks: 7.0.1
  eslint-plugin-react-refresh: 0.4.24
  eslint-plugin-storybook: 10.1.11
  globals: 16.5.0
  motion: 12.24.7
  msw: 2.12.7
  msw-storybook-addon: 2.0.6
  react: 19.2.0
  react-dom: 19.2.0
  react-markdown: 9.0.3
  react-router: 7.11.0
  storybook: 10.1.11
  tailwindcss: 4.1.18
  typescript: 5.9.3
  typescript-eslint: 8.46.4
  vite: 7.2.4
  vite-plugin-dts: 4.5.4
  vite-plugin-lib-inject-css: 2.2.2
  "@chromatic-com/storybook": "^4.1.3"
  "@storybook/addon-vitest": "^10.1.11"
  "@storybook/addon-a11y": "^10.1.11"
  "playwright": "^1.57.0"
  "@vitest/browser-playwright": "^4.0.16"
  "vitest": "^4.0.16"
  "@vitest/coverage-v8": "^4.0.16"
  "@emotion/is-prop-valid": "^1.4.0"
  "remark-breaks": "^4.0.0"