name: SankhyaUI Stories, Sample and Docs

on:
  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    name: Deployment
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
        
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      
      - name: Install all dependencies
        run: pnpm setversion && pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      - name: 📂 Deploy stories
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}.sankhyaui-stories.sankhyatronics.com
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true 
          server-dir: ./public_html/
          local-dir: "Stories/storybook-static"
      
      - name: 📂 Deploy sample
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}.sankhyaui-sample.sankhyatronics.com
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true 
          server-dir: ./public_html/
          local-dir: "Sample/dist"

      - name: 📂 Deploy documentation
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}.sankhyaui.sankhyatronics.com
          password: ${{ secrets.FTP_PASSWORD }}
          dangerous-clean-slate: true 
          server-dir: ./public_html/
          local-dir: "sankhyaui-docs/build"